- name: Docker Setup Initialization
  hosts: 192.168.12.19
  vars:
   - docker_pkg: docker-ce-18.09.1-3.el7.x86_64
   - docker_path: /usr/local/apache2/htdocs
   - httpd_index: /root/pv
   - docker_repo: https://download.docker.com/linux/centos/7/x86_64/stable
  tasks: 
   - name: Configuring Docker Repository
     yum_repository:
       name: Docker
       description: "Docker Repo"
       baseurl: "{{docker_repo}}"
       gpgcheck: no
     register: x

   - name: Checking Configuration Status
     debug:
       var: x.failed

   - name: Installing Docker
     package:
       name: "{{docker_pkg}}"
       state: present
     register: y

   - name: Checking Install Status
     debug:
       var: y.failed

   - name: Starting Docker Daemon
     service:
       name: docker
       state: started
       enabled: yes
     when: y.failed == false

   - name: Install Python packge for Docker
     pip:
       name: docker-py    

   - name: Pull a Docker Image
     docker_image: 
        name: httpd
        tag: latest
        source: pull
     register: z
   - name: Checking Pull Status
     debug: 
       var: z

   - name: Creating a Persistent Volume Dir
     file:
       path: "/root/pv"
       state: directory
       
   - name: Copying the HTML code in the Directory
     copy:
       remote_src: yes        
       src: "/root/index.html"
       dest: "/root/pv"
               


   - name: Launching an HTTPD Container
     when: z.failed == false
     docker_container:
       name: apache-server
       image: httpd
       state: started
       exposed_ports:
         - "80"
       ports:
         - "8888:80"
       volumes: 
         - /root/pv:/usr/local/apache2/htdocs
