- name: Docker_Env_Setup
  hosts: 192.168.12.19
  vars:
    docker_path: /usr/local/apache2/htdocs
    httpd_index: /root/pv
    docker_cent_pkg: docker-ce-18.09.1-3.el7.x86_64
    ver: "{{ansible_distribution_major_version}}"
       
  tasks:
    - name: Checking OS Distro and Major version
      debug: msg="The Distro is {{ansible_distribution}} Major Version is {{ver}}"
       
    - name: For RHEL
      yum_repository:
        name: Docker
        description: "Docker Repo"
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        gpgcheck: no
      when: ansible_facts['distribution'] == "RHEL"
        
    - name: Installing Docker on UBUNTU
      apt:
         name: docker.io
         state: latest
      when: ansible_facts['distribution'] == "Ubuntu"
       
    - name: Installing Docker for RHEL
      when: ansible_facts['distribution'] == "RHEL"
      package:
        name: "{{docker_cent_pkg}}"
        state: present
      

    - name: Starting Docker Daemon
      service:
       name: docker
       state: started
       enabled: yes

    - name: Install Python packge for Docker
      pip:
       name: docker-py    

    - name: Pull a Docker Image
      docker_image: 
        name: httpd
        tag: latest
        source: pull
      register: z
    - name: Checking Pull Status
      debug: 
       var: z

    - name: Creating a Persistent Volume Dir
      file:
        path: "{{httpd_index}}"
        state: directory
       
    - name: Copying the HTML code in the Directory
      copy:
       remote_src: yes        
       src: "/root/index.html"
       dest: "{{httpd_index}}"
               


    - name: Launching an HTTPD Container
      when: z.failed == false
      docker_container:
       name: apache-server
       image: httpd
       state: started
       exposed_ports:
         - "80"
       ports:
         - "8888:80"
       volumes: 
         - "{{httpd_index}}:{{docker_path}}"
