---
- name: Docker playbook
  hosts: 192.168.12.19 
  remote_user: root
  vars:
   docker_img: httpd
   docker_reg_local: localhost:5000/httpd:latest
   docker_path: /usr/local/apache2/htdocs
   httpd_index: /root/pv
  tasks:
   - name: Adding Registry Container Image to Store Images Locally
     docker_image:
       name: registry
       tag: 2
   
   - name: Starting the Registry
     docker_container:
       name: registry
       image: registry:2
       state: started
       exposed_ports:
         - "5000"
       ports:
         - "5000:5000"

   - name: Adding Image From TAR file 
     docker_image:
       name: "{{docker_img}}:latest"
       load_path: "{{docker_img}}.tar"


   - name: Tagging the container
     docker_image:
       name: "{{docker_img}}:latest"
       repository: "{{docker_reg_local}}"

   - name: Pushing Container to Local Registry
     docker_image:
       name: "{{docker_reg_local}}"
       push: yes

#  - name: Tag and push to local registry
#    docker_image:
#      name: localhost:5000/httpd
#      tag: v1
#      push: yes
#      source: load
#      load_path: httpd.tar

   - name: Launching a Container
     docker_container:
       name: apache-server
       image: "{{docker_reg_local}}"
       state: started
       exposed_ports:
         - "80"
       ports:
         - "2525:80"
       volumes:
         - "{{httpd_index}}:{{docker_path}}"  #ACCOMPLISHED
      
