---
- name: Export AAP
  hosts: 192.168.1.40
  vars:
      ansible_python_interpreter: /usr/bin/python3.9
  tasks:
  - name: Installing Galaxy Collection
    shell: ansible-galaxy collection install awx.awx
    register: collection
    
  - name: Installing awxkit
    shell: pip3 install awxkit
    register: awx
    
  - name: checking status for collection
    debug:
      var: collection.stdout_lines
      
  - name: checking status for AWXKIT
    debug:
      var: awx.stdout_lines
      
 
